### ISSUE TITLE
unit test

### ISSUE THREAD

**Issue by scaccogatto** [scaccogatto/vue-waypoint#1]

**Comment by talalzaki** [comment]
i'm new on VueJS and i want install v-waypoint.js with vue2js it's doesn't work," I can not find this problem anywhere, if someone can help me, I'll be grateful, plenty thanks follow my html and js.

--------------------main.js----------------
var App = require('./components/Example.vue')
Vue.component('v-waypoint', {
	name:'app',
  template: '<div>A vue_waypoint component!</div>'
})
new Vue({
  el: '#app',
  render: function (createElement) {
    return createElement(App)
  }
});
--------------------app.vue----------------
<template>
  <div class="vue-waypoint__waypoint">
    <v-waypoint @waypoint-in="inHandler"
                @waypoint-out="outHandler"></v-waypoint>
    <div class="vue-waypoint__waypoint__collider">
      {{ text }}
    </div>
  </div>
</template>

<script>
export default {
  data () {
    return {
      text: 'Hello world!'
    }
  },
   methods: {
      inHandler () {
        this.text = 'going in'
      },
      outHandler () {
        this.text = 'going out'
      }
    }
}
</script>
--------------------index.html----------------
<div id="app">
    <v-waypoint></v-waypoint>
</div>
<script src='js/vue.js'></script>
        <script src='js/vue-waypoint.js'></script>
        <script src='js/main.js'></script>

**Comment by scaccogatto** [comment]
@talalzaki this issue is not what are you looking for, it might be a better choice opening a new issue instead of replying to a "unit test" issue.
I admit that i never tried to use my plugins in a pure browser context so it might be useful if you just send me a **zip file** of your code or, at least, send your console log.

**Comment by nikit-cpp** [comment]
May be this will be useful 
https://scotch.io/tutorials/how-to-write-a-unit-test-for-vuejs

**Comment by scaccogatto** [comment]
Since this is mostly real scroll interaction between the user and the browser, I think we need something like a phantomJS browser and simulate real behaviours. Feel free to contribute.
