### ISSUE TITLE
There is console output by default

### ISSUE THREAD

**Issue by kazdegroot** [scaccogatto/vue-waypoint#15]
Does this console.log serve any purpose beyond debugging:

https://github.com/scaccogatto/vue-waypoint/blob/c35c244c917b433c38175151dac74c21cebdcad0/src/intersectionObserver.js#L15

When using this module with more than a trivial amount of watchers it fills up most of my console history, which makes using it for other purposes very difficult. Hope this can at least be put behind some kind of flag.

Thanks!

**Comment by scaccogatto** [comment]
3fb1f63ad87d57e51173c008562f21fa91d1cc18
