### ISSUE TITLE
direction not setting up properly

### ISSUE THREAD

**Issue by bajras** [scaccogatto/vue-waypoint#16]
I have 2 way points 

```html
<div id="StickyContainer" class="Carousel-wrapper" v-waypoint="{ active: true, callback: onWaypointWrapper }">
  <div :class="{'is-sticky' : headerSticky}">
    <CarouselHeader :titles="plans[0]" v-waypoint="{ active: true, callback: onWaypointHeader }" />
    <div>....</div>
  </div>
</div>
```

```js
data() {
  return {
    headerSticky: false,
    passStickyContainer: false
  };
},
methods: {
  onWaypointHeader({ going, direction }) {
  console.log({going, direction});
    if (going === "out" && direction === "top" && !this.passStickyContainer) {
      this.headerSticky = true;
    }
  },
  onWaypointWrapper({ going, direction }) {
    console.log({going, direction});
    if (going === "out" && direction === "top" && !this.passStickyContainer) {
      this.headerSticky = false;
      this.passStickyContainer = true;
    }
  }
}
```
I have a header that I want to make sticky and then when the container passes the top of the window I want to make the sticky go away. And when I scroll up again I want to make the header sticky.

Im changing the flag of the css and the item gets position static from position fixed and not by scrolling. But when I scroll the container up again I console log `{going: "in", direction: "top"}` where as it should be `{going: "in", direction: "bottom"}`. I dont why its not showing the right flag. But after I scroll up and down again it shows the right flags. Its right after when I remove the class and try to scroll up the container.

**Comment by adityajain15** [comment]
I'm not getting the right flags from my waypoints either. In my case, the speed of my scroll also seems to have an effect on what going and direction are

**Comment by scaccogatto** [comment]
Hello guys,
I am sorry I can't follow the project right now.
Maybe someone could download the project, build it and test with `test/index.html`, looking for this:

https://github.com/scaccogatto/vue-waypoint/blob/master/src/waypointInterface.js#L11
(some debug here could help).

Direction detection in a `position: fixed` context is a bit tricky so, if you find a better way to do it, we can improve the codebase.

**Comment by scaccogatto** [comment]
I think this can be closed because I could not find any issue in 1 year related to this. Maybe it is just bad logic handle.
