### ISSUE TITLE
SSR: window is not defined

### ISSUE THREAD

**Issue by jkosoy** [scaccogatto/vue-waypoint#19]
Hi! Looks like this plugin doesn't work well with Vue SSR. Getting a `ReferenceError: window is not defined` error on compilation. Any thoughts on how to handle?

**Comment by scaccogatto** [comment]
This plugin is not supported in a server context since waypoints are exclusively triggered by user's actions. Probably with some code we can fix this. Anyway i found this: https://github.com/egoist/vue-no-ssr

**Comment by scaccogatto** [comment]
You can put your waypoints under a `v-if="!$isServer"` and try to render.

https://vuejs.org/v2/api/#vm-isServer
