### ISSUE TITLE
vue2js and v-waypoint.js components setup

### ISSUE THREAD

**Issue by talalzaki** [scaccogatto/vue-waypoint#2]
i'm new on VueJS and i want install v-waypoint.js with vue2js it's doesn't work," I can not find this problem anywhere, if someone can help me, I'll be grateful, follow my html and js

<--------- main.js ----->
var App = require('./components/Example.vue')
Vue.component('v-waypoint', {
	name:'app',
  template: '<div>A custom component!</div>' })
new Vue({
  el: '#app',
  render: function (createElement) {
    return createElement(App)
  }
});

<--------- index.html ----->
<div id="app">
 <v-waypoint></v-waypoint>
</div>
<script src='js/vue.js'></script>
<script src='js/vue-waypoints.js'></script>
<script src='js/main.js'></script>

<--------- Example.vue----->
<template>
  <div class="waypoint-test">
    <v-waypoint @waypoint-in="inHandler"
                @waypoint-out="outHandler"></v-waypoint>
    <div class="waypoint-text">
      {{ text }}
    </div>
  </div>
</template>

<script>
  export default {
    data: () => {
      return {
        text: 'not-trigger-yet'
      }
    },
    methods: {
      inHandler () {
        this.text = 'going in'
      },
      outHandler () {
        this.text = 'going out'
      }
    }
  }
</script>

**Comment by scaccogatto** [comment]
Can you send a zip file?

**Comment by talalzaki** [comment]
thank you for your replay.

2017-01-30 8:49 GMT+00:00 scaccogatto <notifications@github.com>:

**Comment by scaccogatto** [comment]
I don't know if your problem is solved, but I think so. If you have any other request please open another ticket.

**Comment by talalzaki** [comment]
I was changing .vue file and when i execute the index.html file on browser, it's show no errors but text varriable still unchanged, thanks. I wait your reponse. I will send you a .zip contains all files.

**Comment by talalzaki** [comment]
the .zip contains all files about mz app

2017-02-01 13:36 GMT+00:00 scaccogatto <notifications@github.com>:

**Comment by scaccogatto** [comment]
You should link it in an external web service or creating a public repo on github (better choice)

**Comment by talalzaki** [comment]
here's .zip
[v-waypoint.zip](https://github.com/scaccogatto/vue-waypoint/files/745702/v-waypoint.zip)

**Comment by talalzaki** [comment]
her's .zip
[app_vwaypoint.zip](https://github.com/scaccogatto/vue-waypoint/files/745716/app_vwaypoint.zip)

**Comment by scaccogatto** [comment]
Your zip file contains only text files and not the project itself. Please provide a full github public repo with the project. I will fork it, fix it (if I can) and make a pull request.

**Comment by scaccogatto** [comment]
This is not an issue with waypoint itself, so I am closing this ticket and similar ones.
