### ISSUE TITLE
threshold, not thresholds

### ISSUE THREAD

**Issue by 4c4-dominique** [scaccogatto/vue-waypoint#20]
In your example on how to use the library

`data: () => ({
    intersectionOptions: {
      root: null,
      rootMargin: '0px 0px 0px 0px',
      **thresholds**: [0]
    } // https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API
  })`

The parameter should be **threshold**,  it won't trigger the waypoints on the desired thresholds (it will still fire when element reaches top of page)

**Comment by scaccogatto** [comment]
You are almost right. Actually you can use `thresholds` as option and your version, `threshold`, is just a shortcut for: `thresholds: [0, 100]`. So I will edit README by this and invite you to read this link: https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API
