### ISSUE TITLE
Documentation has an error in the Javascript

### ISSUE THREAD

**Issue by crazyabdul** [scaccogatto/vue-waypoint#22]
```
intersectionOptions: {
      root: null,
      rootMargin: '0px 0px 0px 0px',
      thresholds: [0, 100]
    } // https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API
```

According to the docs at the link provided, the above code's parameter, `thresholds`, should be `threshold`. That is the only thing that worked for me. 
`thresholds` is not known by the browser, but in my case it seemed to default `threshold` to 1 even though the docs say it should default to 0

Also, `threshold` seems to work only when the target element has a non zero height. I doubt it is a  problem with this plugin but it may help any future users with a similar issue

**Comment by scaccogatto** [comment]
https://w3c.github.io/IntersectionObserver/

```
thresholds, of type FrozenArray<double>, readonly
A list of thresholds, sorted in increasing numeric order, where each threshold is a ratio of intersection area to bounding box area of an observed target. Notifications for a target are generated when any of the thresholds are crossed for that target. If no options.threshold was provided to the IntersectionObserver constructor, the value of this attribute will be [0].```

docs says it is plural.

**Comment by crazyabdul** [comment]
What the doc says and how the plugin behaves seem to differ. I am using v3.2.2 and the waypoint event only fires when the parameter is `threshold` instead of `thresholds`. Below is my intersectionOptions

```
 intersectionOptions: {
      root: null,
      rootMargin: '0px 0px 0px 0px',
      threshold: [0.2, 0.6]
    }
```

**Comment by scaccogatto** [comment]
Okay, I see that they used plural for the `read-only` property and the singular when you declare it. I am merging your PR. Thanks!
