### ISSUE TITLE
Callback function not being run on Edge 15

### ISSUE THREAD

**Issue by ricardosimoes** [scaccogatto/vue-waypoint#25]
Hey! I'm working with vue-waypoint and it works really nice but when I go to Edge 15 the callback function (onWaypoint) doesn't run so my elements get always hidden, never showing up when entring the viewport. Any idea what might be the cause

Thanks!

**Comment by scaccogatto** [comment]
I don't know why you closed this. If you have more (logs, error) we can work on it.
