### ISSUE TITLE
Any plans for making this functioning with nuxt  

### ISSUE THREAD

**Issue by rasikas** [scaccogatto/vue-waypoint#27]
Thanks for the wonderful component. 
I tried to use this in nuxt application even surrounded by `<no-ssr>` tag but I couldn't even import thew library as it throws `window` object reference error. It would be a really help if you can modify this to work with nuxt applications (client side)

**Comment by scaccogatto** [comment]
Try this:
https://nuxtjs.org/guide/plugins/#client-side-only

**Comment by rasikas** [comment]
Thank you, yes it worked, had to use <no-ssr> surrounding the <v-waypoint> too to avoid an error 
```
"The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render."
```
Anyway it is working very well after your suggestion, thanks a lot

**Comment by scaccogatto** [comment]
You can contribute by editing the readme and make this solution a public one.

**Comment by rasikas** [comment]
Yes I will add it to the readme

**Comment by rasikas** [comment]
Looks like github having issues at the moment, cannot fork the repo to edit, I will do as soon as issue github issue is resolved

**Comment by scaccogatto** [comment]
Thank you very much.
