### ISSUE TITLE
vue2js and <v-waypoint> component setup in laravel 5.3

### ISSUE THREAD

**Issue by talalzaki** [scaccogatto/vue-waypoint#3]
I'm new on VueJS and i want to install v-waypoint.js with vue2js it's doesn't work," I can not find this problem anywhere, if someone can help me, I'll be grateful, follow my html and js. plenty of thanks in advance.

[app_laravel 5_3 v-waypoint.pdf](https://github.com/scaccogatto/vue-waypoint/files/746547/app_laravel.5_3.v-waypoint.pdf)

**Comment by scaccogatto** [comment]
Duplicate: issue#2
