### ISSUE TITLE
Having trouble with SSR issue Vue JS

### ISSUE THREAD

**Issue by lfilipos** [scaccogatto/vue-waypoint#31]
I'm having trouble getting this to build when working with Vue JS/Gridsome. I've wrapped the directive component in <ClientOnly> per the [Gridsome documentation](https://deploy-preview-68--gridsome-org-dev.netlify.com/docs/assets-scripts/) and also tried to import it into the mounted hook, but still getting the `ReferenceError: window is not defined`

```
<ClientOnly>
            <div class="hiw-card" id="hiw-deliver"
                 v-waypoint="{active: true, callback: mobScroll, options: intersectionOptions }">
              <h4>Deliver</h4>
              <p>A customers’ data is available via conventional REST API, as well as via a digital wallet, as
                frequently
                as energy is read and CO2e offset/liability calculated (continuously), and as frequently as RECs are
                accumulated in mWh bundles.
              </p>
              <b-row class="justify-content-center">
                <b-col cols="3">
                  <i class="fas fa-database fa-3x hiw-icon"></i>
                </b-col>
                <b-col cols="3">
                  <i class="far fa-long-arrow-alt-right fa-3x hiw-icon"></i>
                </b-col>
                <b-col cols="3">
                  <i class="far fa-user fa-3x hiw-icon"></i>
                </b-col>
              </b-row>
            </div>
          </ClientOnly>
```

```
mounted () {
            window.waypoint = require('vue-waypoint')
    }
```

**Comment by scaccogatto** [comment]
With Nuxt you can load a plugin for the client only.
This library contains a component and a public code that allows you to access the waypoint features even outside the component itself.

Probably, `ClientOnly` is not enough: you are loading the directive in client side code but the rest of the code is still loaded.

Nuxt has a system that loads the whole plugin in client-only mode, you should look for the same feature in Gridsome.

In this very moment I am not planning any project using Gridsome so, if you find a solution, a pull request would be great.

**Comment by sebj54** [comment]
Hi @scaccogatto, I encountered the same problem with Gridsome today.

I finally managed to make it work though! The `window is not defined` error is caused by the `intersection-observer` package. Maybe you can provide a dist file without this polyfill so we can import it in our Gridsome app?

To make it work, I copied the `src` directory from your package in a `plugins/vue-waypoint` directory and just change this line in `intersectionObserver.js`:

```diff
- import {} from 'intersection-observer'
+ if (process.isClient) {
+   require('intersection-observer')
+ }
```

I don't see what else you can do with your plugin to address this issue…

**Comment by scaccogatto** [comment]
Well, since it's 2020 we can remove that polyfill from the codebase and dependencies -> bump the version up with a major release and deploy.

You can do it by yourself with a PR or wait for me. I think I can handle this next week maybe.

**Comment by scaccogatto** [comment]
This commit:
5973a5e34b063bba3f133640004c2d12fcca0dfc
removes the polyfill.

Remember to include the polyfill by yourself if needed.
I would like to hear some feedback from Gridsome users.

**Comment by sebj54** [comment]
Great! Thanks for the update, I'll test it in the next days and let you know.

**Comment by sebj54** [comment]
Works like a charm now!

I just needed this in my `main.js` file:

```javascript
import VueWaypoint from 'vue-waypoint'

export default function(Vue}) {
    Vue.use(VueMasonry)
}
```

Thanks for your awesome plugin!

**Comment by scaccogatto** [comment]
Great!
