### ISSUE TITLE
Typo in `defineDirective`

### ISSUE THREAD

**Issue by sa16ot** [scaccogatto/vue-waypoint#35]
There is a typo in `defineDirective` function. It is `update` hook function, not `updated`

See https://vuejs.org/v2/guide/custom-directive.html#Hook-Functions

**Comment by scaccogatto** [comment]
Thanks for your ticket, can you address the issue and fix it?
I am thinking of switching from `update` to `componentUpdated` so reduce the overhead.

**Comment by sa16ot** [comment]
> I am thinking of switching from `update` to `componentUpdated` so reduce the overhead.
Not sure it's really needed since we don't care about children elements
