### ISSUE TITLE
element stays 'active' if threshold is different than '0' or '1'

### ISSUE THREAD

**Issue by Saurou** [scaccogatto/vue-waypoint#37]
Looks like 'going' is changing to 'out' in an inconsistent way when the threshold is not 0 or 1.
On the example looks like it works when scrolling the page to top or bottom really fast.

**Comment by scaccogatto** [comment]
I never had this issue with my library but I heard about this sometimes.
I don't think is related to the library itself but on how the IO API are implemented.
