### ISSUE TITLE
[Question] How can i load a component using waypoint?

### ISSUE THREAD

**Issue by emjimadhu** [scaccogatto/vue-waypoint#4]
Say i have three components in a parent component, i want to make those three child components load only when its visible in viewport. how can i do that?

**Comment by scaccogatto** [comment]
Nice question but is not related on this plugin anyway.

You should use `v-if` as follows:

```
<v-waypoint @waypoint-in="visible = true"></v-waypoint>

...

<component v-if="visible"></component>
<component v-if="visible"></component>
<component v-if="visible"></component>

...

export default {
  data: () => { return { visible: false } }
```

**Comment by emjimadhu** [comment]
hi thank you sooooo much.. im very new to vue.. thats why that silly question.. but unfortunatly the solution you given was not working.. my components are loading on the initial load itself.. :(

**Comment by scaccogatto** [comment]
You should create a public repo and let me or others fork and solve the problem for you.

**Comment by scaccogatto** [comment]
I will let this open for some day in order to post the repo's link, then I will close it since it's not project-related
