### ISSUE TITLE
Version 3.4.2 wasn't published, switching to github actions

### ISSUE THREAD

**Issue by denisgruba** [scaccogatto/vue-waypoint#40]
Hello! I'm currently relying on toggling the active state in the runtime, but the latest published version on npm is 3.4.1.
Could you publish the latest version so it's in-line with the state on github, please?

**Comment by scaccogatto** [comment]
I am abusing this request to update the build tools to github actions

**Comment by scaccogatto** [comment]
this should solve it

**Comment by scaccogatto** [comment]
it seems solved, can you confirm?

**Comment by denisgruba** [comment]
I can confirm it works all good now, thank you! 👍
