### ISSUE TITLE
Threshold: [0, 0.01, ...0.99, 1 ] not being triggered.

### ISSUE THREAD

**Issue by genesisneo** [scaccogatto/vue-waypoint#42]
Using Nuxt.js having threshold like the following:
```
data () {
  return {
    wayPointOptions: {
      root: null,
      rootMargin: '0px 0px 0px 0px',
      threshold: Array(101).join(0).split(0).map((n, i) => (i) / 100) // [0.00, 0.01, ...0.99, 1]
    }
  }
}
```
or ` threshold: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]`, call back is not being triggered.
element sample:
```
<section v-waypoint="{ active: true, callback: onWaypoint, options: { wayPointOptions } }">
  ...
</section>
```
**UPDATE**
Adding threshold inline instead of data works fine 🤔
```
<section
  v-waypoint="{
    active: true,
    callback: onWaypoint,
    options: {
      threshold: Array(101).join(0).split(0).map((n, i) => (i) / 100)
    }
  }"
>
  ...
</section>
```

**Comment by scaccogatto** [comment]
Maybe is related to something like reactivity. We should investigate more.

**Comment by genesisneo** [comment]
Found the culprit. The issue is:
❌ `options: { wayPointOptions }`
where it should be
✅ `options: wayPointOptions`
Closing issue. Thanks for the plugins though.
