### ISSUE TITLE
knowing last callback is possible?

### ISSUE THREAD

**Issue by yasinakbulut** [scaccogatto/vue-waypoint#45]
how to catch last callback for elements that appear on the screen ?

**Comment by scaccogatto** [comment]
```js
export default {
  data: () => ({
    lastCb: undefined
  })
  methods: {
    onWaypoint (e) {
      this.lastCb = e
    }
  }
}
```

**Comment by yasinakbulut** [comment]
<li v-waypoint="{ active: true, callback: onWaypoint }"></li>
<li v-waypoint="{ active: true, callback: onWaypoint }"></li>
<li v-waypoint="{ active: true, callback: onWaypoint }"></li>
<li v-waypoint="{ active: true, callback: onWaypoint }"></li>
<li v-waypoint="{ active: true, callback: onWaypoint }"></li>
<li v-waypoint="{ active: true, callback: onWaypoint }"></li>
<li v-waypoint="{ active: true, callback: onWaypoint }"></li>
<li v-waypoint="{ active: true, callback: onWaypoint }"></li>

code you share, does not help me. when these elements appear on the screen, i have 8 callbacks. i just need last one. and when scroll down there is more li elements. last callback or multiple that i need

**Comment by scaccogatto** [comment]
I cannot understand you, sorry.

**Comment by yasinakbulut** [comment]
ok thanks.
