### ISSUE TITLE
Vue 3 waypoint map element

### ISSUE THREAD

**Issue by leightonhughes** [scaccogatto/vue-waypoint#59]
Is there a way to implement `this.$waypointMap` on the Vue 3 version of waypoint?

I had used this on the Vue 2 version but doesn't look to be documented on the new one. I'm wanting to just add one class and disable the going and direction.

`methods: {
    onWaypoint({ el, going, direction }) {
      if (going === this.$waypointMap.GOING_IN) {
        el.classList.add('waypoint')
      }
    },
  },`

**Comment by scaccogatto** [comment]
4.2.0 version now supports disabling CSS helpers:
https://github.com/scaccogatto/vue-waypoint#disablecsshelpers

For custom classes, you can use the ` callback`  fired at every` @change` event.
https://github.com/scaccogatto/vue-waypoint#change
