### ISSUE TITLE
how can i use offset

### ISSUE THREAD

**Issue by jackwangwj** [scaccogatto/vue-waypoint#6]
How can I use offset

**Comment by scaccogatto** [comment]
This library actually draws a `div` into your DOM and checks for collisions. If you want to make your collision trigger before or after some pixels (offset) you need to style the waypoint accordingly:
1. Set a new class on your waypoint: `<v-waypoint class="custom-waypoint-class' @waypoint="waypointHandler"></v-waypoint>`
2. Style your class: `.custom-waypoint-class { margin-top: -10px; }`

`-10px` will be your negative offset (that means the waypoint will trigger 10px **before** its original position)

You can try it by yourself and send a pull request with an updated README that explains the thing.

**Comment by scaccogatto** [comment]
I will close this since it seems the "problem" is solved.
