### ISSUE TITLE
Could not find a typescript declaration file for module 'vue-waypoint'

### ISSUE THREAD

**Issue by Q16solver** [scaccogatto/vue-waypoint#74]
Hello! I think there's some issue with the typescript declaration file with vue-waypoint now, previously I remember this was working fine, did the newer versions break it perhaps?

![image](https://user-images.githubusercontent.com/50786287/189270083-9369f4f2-c8e1-412b-a835-cbd7caeabf3d.png)

**Comment by scaccogatto** [comment]
You are right, maybe @iamandrewluca knows better.
I will try to look into this issue soon.

**Comment by iamandrewluca** [comment]
That is strange 🤔 I indicated the `typings` in `package.json`

**Comment by Q16solver** [comment]
@iamandrewluca From ver 4.2.3 to 4.2.4, I suspect it had something to do with a recent change

**Comment by scaccogatto** [comment]
Looking into `package.json`: https://github.com/scaccogatto/vue-waypoint/blob/master/package.json#L8
I see components/index.ts is exported as typing but it actually does not exist.

I'll try with a quick fix.

**Comment by iamandrewluca** [comment]
Oooh, it should be `src/components/Waypoint/index.ts` instead of `src/components/index.ts` 🤦🏼

**Comment by scaccogatto** [comment]
https://github.com/scaccogatto/vue-waypoint/commit/612fd4c8e4c6efdbdc42a06a3c1c5a47ad7a0b49

@Q16solver can you try now? v4.2.5

@iamandrewluca don't worry about that!

**Comment by Q16solver** [comment]
@scaccogatto @iamandrewluca Works like a charm! Closing this issue
