### ISSUE TITLE
How to use it, why not to provide example?

### ISSUE THREAD

**Issue by iamdubx** [scaccogatto/vue-waypoint#9]
Hi. I got this from docs but this doesn't tell me how to use this plugin

```
<template>
  <div class="waypoint-test">
    <v-waypoint @waypoint-in="inHandler"
                @waypoint-out="outHandler"></v-waypoint>
    <div class="waypoint-text">
      {{ text }}
    </div>
  </div>
</template>

<script>
import Vue from 'vue'
import VueWaypoint from 'vue-waypoint'

Vue.use(VueWaypoint)
export default {
  data: () => {
    return {
      text: 'not-trigger-yet'
    }
  },
  methods: {
    inHandler () {
      this.text = 'going in'
    },
    outHandler () {
      this.text = 'going out'
    }
  }
}
</script>
```
It just says `going in` in empty page. 
Please explain how to use it.

**Comment by scaccogatto** [comment]
It seems You didn't read the whole documentation:
- [waypoint definition](https://github.com/scaccogatto/vue-waypoint#what-is-a-waypoint)

If you put that component in an empty page it will just trigger instantly (showing you `going in` as expected)
Read the documentation again and try it in a real context, maybe put the waypoint component far from the render viewport.
